[package]
name = "ascworld-01"
version = "0.1.0"
authors = ["Javier Pollak <javi.po.123@gmail.com>"]

[profile.release]
opt-level = 3
debug = false
lto = true

[profile.dev]
opt-level = 3
lto = true

[dependencies]
ndarray = "0.11"
termion = "1.5"
